[package]
name = "reth-rpc-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Reth RPC types
"""

[dependencies]
# reth
reth-primitives = { workspace = true }
reth-rlp = { workspace = true }

# errors
thiserror = { workspace = true }

# misc
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
jsonrpsee-types = { version = "0.18" }

[dev-dependencies]
# reth
reth-interfaces = { workspace = true, features = ["test-utils"] }

# misc
rand = { workspace = true }
assert_matches = "1.5"
similar-asserts = "1.4"
